---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "250m"
              memory: "245Mi"
            limits:
              cpu: "1"
              memory: "1G"
          env:
            - name: PORT
              value: "8001"
            - name: UNIQP_APP_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: UNIQP_DEBUG
              value: "1"
            - name: UNIQP_ALLOWED_HOSTS
              value: "www.uniqpanel.app,uniqpanel.app,$(NGINX_SERVICE_HOST),127.0.0.1"
            - name: UNIQP_ALLOWED_CIDR
              value: "$(UNIQP_APP_POD_IP)/20,$(NGINX_SERVICE_HOST)/20"
          envFrom:
            - secretRef:
                name: uniqpanel-env
          # TODO: pin this and enable automated deploys
          image: us.gcr.io/kizuna-188702/github.com/austinpray/uniqpanel/app:PLACEHOLDER
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              cpu: "250m"
              memory: "245Mi"
            limits:
              cpu: "1"
              memory: "1G"
          env:
            - name: NGINX_PROXY_PASS
              value: app.uniqpanel.svc.cluster.local:8001
          envFrom:
            - secretRef:
                name: uniqpanel-env
          # TODO: pin this and enable automated deploys
          image: us.gcr.io/kizuna-188702/github.com/austinpray/uniqpanel/nginx:PLACEHOLDER
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 50

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: uniqpanel-dot-app
spec:
  domains:
    - uniqpanel.app
    - www.uniqpanel.app

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx"
  labels:
    app: "nginx"
  annotations:
    cloud.google.com/backend-config: '{"default": "nginx-backendconfig"}'
    networking.gke.io/v1beta1.FrontendConfig: "nginx-frontendconfig"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "nginx"
  type: "NodePort"

---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: nginx-backendconfig
spec:
  # 1 hour lol, uploads
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: nginx-frontendconfig
spec:
  redirectToHttps:
    enabled: true

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: uniqpanel-dot-app
    networking.gke.io/managed-certificates: uniqpanel-dot-app
spec:
  backend:
    serviceName: nginx
    servicePort: 80

