apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uniqpanel
resources:
- namespace.yaml
- deployment.yaml

secretGenerator:
- envs:
  - .env.production
  name: uniqpanel-env

images:
- digest: sha256:bf664fdd8346739e8f9cbb924210f7be7c8a512bc05dea4dbedf5b752df06d17
  name: us.gcr.io/kizuna-188702/github.com/austinpray/uniqpanel/app
- digest: sha256:56031d9f57f4acf53c14dce10b5614290a7554f594be65ce1ae9109139f90d5c
  name: us.gcr.io/kizuna-188702/github.com/austinpray/uniqpanel/nginx
