apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uniqpanel
resources:
- namespace.yaml
- deployment.yaml

secretGenerator:
- envs:
  - .env.production
  name: uniqpanel-env

images:
- digest: sha256:ccbdd475bf9d06439f62062091280cceceacfa688cbefb5ad093799dd6e8beb6
  name: us.gcr.io/kizuna-188702/github.com/austinpray/uniqpanel/app
- digest: sha256:b581ac8be1be3101ceeefb65051f27dadb82eaf17e45282ca3b1fa5dbfe02e04
  name: us.gcr.io/kizuna-188702/github.com/austinpray/uniqpanel/nginx
